version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20       
  pre_build:
    commands:
      - echo Logging in to Amazon ECR.....
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=041042815388.dkr.ecr.ap-south-1.amazonaws.com/aws-ecrcli-nginx
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - ls 
#       - sudo systemctl enable docker.service
#       - sudo systemctl start docker.service
#       - sudo systemctl status docker.service
      - docker build -t 041042815388.dkr.ecr.ap-south-1.amazonaws.com/aws-ecrcli-nginx:test .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 041042815388.dkr.ecr.ap-south-1.amazonaws.com/aws-ecrcli-nginx:test
      - echo Writing image definitions file...
      - printf '[{"name":"nginx","imageUri":"%s"}]' 041042815388.dkr.ecr.ap-south-1.amazonaws.com/aws-ecrcli-nginx:test > imagedefinitions.json
artifacts:
    files: imagedefinitions.json      
